package com.pengpp.apt.utils;

public class Consts {
    // Log
    static final String PROJECT = "Pengpp";
    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";
    private static final String FACADE_PACKAGE = "com.pengpp.annotations";
    public static final String ANNOTATION_TYPE_JSON = FACADE_PACKAGE + ".PConfig";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY PConfig.";
}
